# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # For Python dependencies in requirements.txt or Pipfile
  - package-ecosystem: "pip"
    directory: "/" # Location of requirements.txt or Pipfile
    schedule:
      interval: "weekly"

  # Optional: For GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/" # GitHub Actions live in .github/workflows
    schedule:
      interval: "weekly"
